### ISSUE TITLE
make 错误

### ISSUE THREAD

**Issue by wangning7149** [MegEngine/MegPeak#5]
我的cmake 命令是 ： cmake ..
然后再执行make 命令出现以下错误：
In file included from /usr/local/gcc-5.4/include/c++/5.4.0/chrono:35:0,
                        from /data/ningwang11/MePeak-main/src/cpu/common.h:13
                        from /data/ningwang11/Mepeak-main/src/cpu/aarch64.cpp:11:
/usr/local/gcc-5.4/include/c++/5.4.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support \

In file included from /data/ningwang11/Mepeak-main/src/cpu/aarch64.cpp:11:0
/data/ningwang11/Mepeak-main/src/cpu/common.h:22:1:error: 'constexpr' does not name a type 
constexpr static unint32_t RUNS = 800000

*********************************************************************************************
请问这个错误该怎么解决啊？

**Comment by chenqy4933** [comment]
> error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

看上去是编译器版本过低，换一个高一点的编译器版本吧

**Comment by wangning7149** [comment]
> 

解决了，cmakelists.txt里面加上ISO的信息，😁😁

**Comment by chenqy4933** [comment]
欢迎PR， @wangning7149
