### ISSUE TITLE
寒武纪MLU 上测试opencl 出错

### ISSUE THREAD

**Issue by wangning7149** [MegEngine/MegPeak#7]
在寒武纪芯加速卡MLU上测试 ，运行 ./megpeak -d opencl时，出现以下错误：

use opencl  error:/usr/lib64/libOpenCL.so
opencl error -1001: unknow error (clGetPlatformIDs(0,nullptr,&nr_platforms) at /data/....../MegPeak-main/src/opencl/common.cpp:OpenCLEnv:438)

请问这是MLU不支持openCL导致的吗？

**Comment by chenqy4933** [comment]
看上去已经找到了OpenCL的驱动了，说明MLU是支持OpenCL的，但是调用它的OpenCL的接口挂了，具体细节不太清楚，没有在MLU上运行过，你可以找一个OpenCL的最小demo，看看能不能在MLU上跑起来。

**Comment by wangning7149** [comment]
> 看上去已经找到了OpenCL的驱动了，说明MLU是支持OpenCL的，但是调用它的OpenCL的接口挂了，具体细节不太清楚，没有在MLU上运行过，你可以找一个OpenCL的最小demo，看看能不能在MLU上跑起来。

好的
